# Numpy套件

In [ ]:
a = [1,2,3,4,5]
print(a*3)

## numpy套件的ndarray型態，提供element-wise的操作

In [3]:
import numpy as np # 多維陣列
b = np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [5]:
print(type(b))
print(b.ndim)#ndarray的維度
print(b.shape)#ndarray的shape
print(b.dtype)#ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [12]:
print(np.zeros(6))#產生一維度的陣列
print(np.zeros((3,6)))#產生二維度的陣列
print(np.zeros((2,3,6)))#產生三維度的陣列


[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [15]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4))#改變資料的維度為4X4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


## ndarray的進階操作

In [17]:
print(np.arange(11))#產生一個0~10的一維陣列

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #取0,1,2,3,4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [26]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b = np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c = np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# 二維ndarray取值

In [2]:
import numpy as np
my_2d_array = np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:])#第0列的元素
print(my_2d_array[1,:])#第1列的元素
print(my_2d_array[:,0])#第0欄的元素
print(my_2d_array[1,1])#第2列第2欄的元素


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


# 假設六組 "modern web","devops","cloud","big data","security","自我挑戰組"。參與人數分別為56,8,19,14,6,71

In [1]:
import numpy as np
groups = ["modern web","devops","cloud","big data","security","自我挑戰組"]
ironman = [56,8,19,14,6,71]
groups_array = np.array(groups)
ironman_array = np.array(ironman)
print(groups_array)
print(ironman_array)

['modern web' 'devops' 'cloud' 'big data' 'security' '自我挑戰組']
[56  8 19 14  6 71]


# 篩選大於十人的組別

In [6]:
#用人數篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])

[ True False  True  True False  True]
['modern web' 'cloud' 'big data' '自我挑戰組']


# 除自我挑戰組以外人數?

In [9]:
#用組別篩選人數
print(groups_array!="自我挑戰組")
print(ironman_array[groups_array!="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


# ndarray空值nan無限大inf

In [11]:
nan_array = np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# 生成10組標準常態分配(平均為零，標準差為1的常態分配)隨機變數

In [12]:
normal_samples = np.random.normal(size = 10)
print(normal_samples)

[ 0.23374088 -1.39891087 -0.14590497  0.66815314  0.9230439  -1.7344874
  1.61501753 -0.24655888 -1.89221612  1.3062149 ]


# 生成10組介於0-1的之間的隨機變數

In [16]:
uniform_samples = np.random.uniform(size = 10)
print(uniform_samples)

[0.01892225 0.29086798 0.82421844 0.22501099 0.68411741 0.64607685
 0.3456472  0.48425643 0.47608566 0.59732918]
